"""Core package -- abstract base classes and marker interfaces.

Covers CQRS, DDD, and Event Sourcing. Sub-packages follow the ABCDEF Venn diagram:
  c/   -- CQRS only
  d/   -- DDD only
  de/  -- DDD + Event Sourcing (includes Event hierarchy)
"""

from .c import (
    Command,
    CommandBus,
    CommandHandler,
    CommandRegistry,
    Document,
    DocumentStore,
    EventBus,
    Message,
    MessageBus,
    Query,
    QueryBus,
    QueryHandler,
    QueryRegistry,
    Result,
    TCommand,
    TQuery,
    TQueryResult,
    TResult,
)
from .c.markers import (
    command,
    command_handler,
    document,
    document_store,
    projector,
    query,
    query_handler,
)
from .d import (
    AggregateId,
    AggregateRoot,
    Repository,
    ValueObject,
)
from .d.markers import (
    aggregate,
    domain_service,
    factory,
    identifier,
    repository,
    specification,
    value_object,
)
from .de import (
    AggregateRecord,
    AggregateState,
    AggregateStore,
    DomainEvent,
    Event,
    EventSourcedAggregate,
    EventSourcedRepository,
    EventStore,
    VersionConflictError,
    event_store,
)
from .markers import _get_marker

__all__ = [
    "AggregateId",
    "AggregateRecord",
    "AggregateRoot",
    "AggregateState",
    "AggregateStore",
    "Command",
    "CommandBus",
    "CommandHandler",
    "CommandRegistry",
    "Document",
    "DocumentStore",
    "DomainEvent",
    "Event",
    "EventBus",
    "EventSourcedAggregate",
    "EventSourcedRepository",
    "EventStore",
    "Message",
    "MessageBus",
    "Query",
    "QueryBus",
    "QueryHandler",
    "QueryRegistry",
    "Repository",
    "Result",
    "TCommand",
    "TQuery",
    "TQueryResult",
    "TResult",
    "ValueObject",
    "VersionConflictError",
    "_get_marker",
    "aggregate",
    "command",
    "command_handler",
    "document",
    "document_store",
    "domain_service",
    "event_store",
    "factory",
    "identifier",
    "projector",
    "query",
    "query_handler",
    "repository",
    "specification",
    "value_object",
]
